name: Photos App DWH
services:
  oltp:
    container_name: oltp
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${OLTP_USER}
      POSTGRES_PASSWORD: ${OLTP_PASSWORD}
      POSTGRES_DB: ${OLTP_DB_NAME}
    ports:
      - "${OLTP_EXTERNAL_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./db_creation_scripts/oltp:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/csv_imports:ro
      - ./etl/csvToOltp:/opt/etl_scripts:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${OLTP_USER}" ]
      interval: 2s
      timeout: 10s
      retries: 5
